# Generated by Django 3.0.1 on 2019-12-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
