# Generated by Django 3.0.1 on 2019-12-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
